# Generated by Django 2.2.1 on 2019-05-12 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(help_text='Locality', max_length=64)),
                ('city', models.CharField(help_text='City', max_length=64)),
                ('state', models.CharField(help_text='State', max_length=64)),
                ('zip_pin_code', models.IntegerField(help_text='Zip/Pin code')),
                ('country', models.CharField(help_text='Country', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MERCHANT_KEY', models.CharField(help_text='Merchant Key from PayU Money', max_length=64)),
                ('MERCHANT_SALT', models.CharField(help_text='Merchant Salt from PayU Money', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, help_text='Associated Website', null=True)),
                ('phone_number', models.IntegerField(help_text='Phone number')),
                ('mobile_number', models.IntegerField(blank=True, help_text='Mobile number', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter facilities provided', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a hobby (e.g. cricket, football, gardening)', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter income source', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Orphan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=64)),
                ('last_name', models.CharField(help_text='Last Name', max_length=64)),
                ('dob', models.DateField(help_text='Date of Birth')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], help_text='Gender', max_length=1)),
                ('status', models.CharField(choices=[('a', 'Available'), ('n', 'Not Available'), ('u', 'Unknown')], default='a', help_text='Adoption Status', max_length=1)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('education', models.CharField(blank=True, help_text='Education', max_length=64)),
                ('avatar', models.ImageField(blank=True, height_field=4.5, null=True, upload_to='orphans_dp/', width_field=3.5)),
                ('hobbies', models.ManyToManyField(blank=True, help_text='Select hobbies', to='home.Hobby')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Orphanage',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(help_text='Name of Orphanage', max_length=256)),
                ('reg_num', models.CharField(help_text='Registration number', max_length=255, unique=True)),
                ('date_estd', models.DateField(blank=True, help_text='Date of establishment', null=True)),
                ('brief_desc', models.TextField(help_text='Brief description of Orphanage', max_length=512)),
                ('total_donation_raised', models.FloatField(help_text='Total donation raised through this website')),
                ('display_pic', models.ImageField(blank=True, height_field=4.5, null=True, upload_to='orphanage_dp/', width_field=3.5)),
                ('address', models.OneToOneField(help_text='Address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Address')),
                ('bank_details', models.OneToOneField(help_text='Bank details', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.BankDetail')),
                ('contact', models.OneToOneField(help_text='Contact', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Contact')),
                ('facilities', models.ManyToManyField(help_text='Facilities Available', to='home.Facilities')),
                ('income_source', models.ManyToManyField(help_text='Source of Income', to='home.IncomeSource')),
            ],
            options={
                'ordering': ['name', 'date_estd'],
            },
        ),
        migrations.CreateModel(
            name='OrphansImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image', null=True, upload_to=home.models.uploaded_dir)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Orphan')),
            ],
        ),
        migrations.CreateModel(
            name='OrphanagesImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image', null=True, upload_to=home.models.uploaded_dir)),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Orphanage')),
            ],
        ),
        migrations.AddField(
            model_name='orphan',
            name='orphanage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Orphanage'),
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='First Name', max_length=64)),
                ('last_name', models.CharField(blank=True, help_text='Last Name', max_length=64)),
                ('date', models.DateField(auto_now_add=True, help_text='Donation date/time')),
                ('phone_number', models.IntegerField(blank=True, help_text='Phone number', null=True)),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=254, null=True)),
                ('amount_donated', models.FloatField(help_text='Donation Amount')),
                ('donated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Orphanage')),
            ],
            options={
                'ordering': ['first_name', 'last_name', 'amount_donated'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=64)),
                ('last_name', models.CharField(help_text='Last Name', max_length=64)),
                ('date', models.DateField(auto_now_add=True, help_text='Adoption request date/time')),
                ('dob', models.DateField(help_text='Date of Birth (For age purpose)')),
                ('phone_number', models.IntegerField(help_text='Phone number')),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=254, null=True)),
                ('occupation', models.CharField(help_text='Occupation', max_length=64)),
                ('income', models.IntegerField(help_text='Annual income')),
                ('married', models.CharField(choices=[('m', 'Married'), ('u', 'Un-married')], help_text='Marriage Status', max_length=1)),
                ('num_family_mem', models.IntegerField(verbose_name='Total number of family members')),
                ('address', models.OneToOneField(help_text='Address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Address')),
                ('requested_for', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Orphan')),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Orphanage')),
            ],
        ),
    ]
