# Generated by Django 2.2.1 on 2019-05-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190516_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphan',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='orphans_dp/'),
        ),
        migrations.AlterField(
            model_name='orphanage',
            name='display_pic',
            field=models.ImageField(blank=True, null=True, upload_to='orphanage_dp/'),
        ),
    ]
