# Generated by Django 2.2.1 on 2019-05-16 07:31

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190516_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphansimages',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image', null=True, upload_to=home.models.uploaded_dir_orphans),
        ),
    ]
