# Generated by Django 2.2.1 on 2019-05-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190517_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphanage',
            name='display_pic',
            field=models.ImageField(blank=True, help_text='Display picture for orphanage', null=True, upload_to='orphanage_dp/'),
        ),
    ]
