# Generated by Django 2.2.1 on 2019-06-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190517_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetail',
            old_name='MERCHANT_KEY',
            new_name='merchant_key',
        ),
        migrations.RenameField(
            model_name='bankdetail',
            old_name='MERCHANT_SALT',
            new_name='merchant_salt',
        ),
    ]
