# Generated by Django 2.2.1 on 2019-06-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190609_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphanage',
            name='facilities',
            field=models.ManyToManyField(blank=True, help_text='Facilities Available', to='home.Facilities'),
        ),
        migrations.AlterField(
            model_name='orphanage',
            name='income_source',
            field=models.ManyToManyField(blank=True, help_text='Source of Income', to='home.IncomeSource'),
        ),
    ]
