# Generated by Django 2.2.1 on 2019-06-15 07:49

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_adoptionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('first_name', models.CharField(help_text='First Name', max_length=64)),
                ('last_name', models.CharField(help_text='Last Name', max_length=64)),
                ('request_id', models.CharField(default=home.models.generate_urid, editable=False, max_length=18, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, help_text='Adoption request date/time')),
                ('dob', models.DateField(help_text='Date of Birth (For age purpose)')),
                ('phone_number', models.CharField(help_text='Phone number', max_length=32)),
                ('email', models.EmailField(help_text='Email', max_length=254, null=True)),
                ('occupation', models.CharField(help_text='Occupation', max_length=64)),
                ('income', models.FloatField(help_text='Annual income')),
                ('married', models.CharField(choices=[('m', 'Married'), ('u', 'Un-married'), ('d', 'Divorced')], help_text='Marriage Status', max_length=1)),
                ('family_members', models.IntegerField(verbose_name='Total number of family members')),
                ('address', models.OneToOneField(help_text='Address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Address')),
                ('requested_for', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Orphan')),
                ('requested_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Orphanage')),
            ],
        ),
    ]
