# Generated by Django 2.2.1 on 2019-06-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_adoptionrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionrequest',
            old_name='date',
            new_name='request_date',
        ),
    ]
