# Generated by Django 2.2.1 on 2019-06-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190615_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='requested_to',
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='requested_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Orphan'),
        ),
    ]
