# Generated by Django 2.2.1 on 2019-06-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190615_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Adoption request date/time'),
        ),
    ]
