# Generated by Django 2.2.1 on 2019-06-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190617_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_pin_code',
            field=models.CharField(help_text='Zip/Pin code', max_length=12),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='approved',
            field=models.CharField(choices=[('a', 'Approved'), ('d', 'Declined'), ('p', 'Pending')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='donor',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Donation date/time'),
        ),
    ]
