# Generated by Django 2.2.1 on 2019-06-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190628_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='txnid',
        ),
        migrations.AddField(
            model_name='donor',
            name='payuMoneyId',
            field=models.CharField(help_text='payu Money ID', max_length=20, null=True, unique=True),
        ),
    ]
