# Generated by Django 2.2.1 on 2019-06-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_orphanage_total_donation_raised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphanage',
            name='display_pic',
            field=models.ImageField(blank=True, default='dream_home.gif', help_text='Display picture for orphanage', null=True, upload_to='orphanage_dp/'),
        ),
    ]
