# Generated by Django 2.2.1 on 2019-06-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190629_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanage',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Activated'),
        ),
    ]
