# Generated by Django 2.2.1 on 2019-06-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_orphanage_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphanage',
            name='bank_details',
            field=models.OneToOneField(blank=True, help_text='Bank details', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.BankDetail'),
        ),
    ]
